### DISCUSSION TITLE
CSI Controller not recognizing cluster TLS CA authority

### DISCUSSION THREAD

**Discussion by derselbst** [weka/csi-wekafs#174] [Q&A] [answered]
Previously, we've used `http` as `scheme` in the weka-api-secret for testing purposes which works fine.

For production, we would like to switch to `https` as `scheme`. However,  the wekafs container of the controller pod fails to establish a connection with  the management endpoint:

```
2023-10-25T19:15:53.557Z ERR apiclient.go:450 > error="Post \"https://retracted.mydomain.org:14000/api/v2/login\": tls: failed to verify certificate: x509: certificate signed by unknown authority" op=CreateVolume span_id=fe4e2cf0059da66f trace_id=6d21f0c9a2865d587e8e4ba3ce8ce73b
2023-10-25T19:15:53.557Z ERR wekafs.go:142 > Failed to initialize API client error="Post \"https://retracted.mydomain.org:14000/api/v2/login\": tls: failed to verify certificate: x509: certificate signed by unknown authority" op=CreateVolume span_id=fe4e2cf0059da66f trace_id=6d21f0c9a2865d587e8e4ba3ce8ce73b
2023-10-25T19:15:53.557Z ERR wekafs.go:189 > Failed to initialize API client from secret, cannot proceed error="Post \"https://retracted.mydomain.org:14000/api/v2/login\": tls: failed to verify certificate: x509: certificate signed by unknown authority" op=CreateVolume span_id=fe4e2cf0059da66f trace_id=6d21f0c9a2865d587e8e4ba3ce8ce73b
2023-10-25T19:15:53.557Z ERR controllerserver.go:220 > <<<< Completed processing request op=CreateVolume result=FAILURE span_id=fe4e2cf0059da66f trace_id=6d21f0c9a2865d587e8e4ba3ce8ce73b
```

### Additional context

We have installed a custom TLS certificate for our cluster via `weka security ca-cert set`. The certificate is correctly presented when accessing _any_ management endpoint via the web-browser (i.e. it includes SANs for all nodes).  The certificate itself has been issued by "Atos TrustedRoot 2011". I have checked that the CA-bundle of the `wekafs` container of the controller pod (located at `/etc/ssl/certs/ca-certificates.crt` inside the container) and it does contain the base64 encoded `Atos TrustedRoot 2011` CA. I would therefore expect, that the controller recognizes the authenticity of the certificate.

Is a different CA store used by the `wekafsplugin`? Is this even the right place to discuss this or should I address it directly to the Weka support?

Sidenote: The `endpoints` in the weka-api-secret are given as DNS names, not IP addresses, as IPs are not included in the SANs of the cluster TLS certificate, which shouldn't matter though.

**Comment by sergeyberezansky** [comment]
1. you can provide FQDNs as well, not necessarily use IP addresses.
2. if IP addresses are not added as additional SAN, not trusting a certificate is an expected behavior
3. You can still allow communication by modifying `.pluginConfig.allowInsecureHttps` to true (https://github.com/weka/csi-wekafs/blob/main/charts/csi-wekafsplugin/values.yaml)

**Reply by sergeyberezansky** [reply]
The CA certificate store trusted by CSI plugin is basically the store defined in Alpine Linux container, and it does not rely on the kubernetes node certificate store.

**Reply by derselbst** [reply]
> The CA certificate store trusted by CSI plugin is basically the store defined in Alpine Linux container

I was referring to that CA store in the alpine container. It contains the CA, which is why I didn't expect to get this error message. I don't want to disable TLS validation.

**Reply by sergeyberezansky** [reply]
Thank you @derselbst 
Indeed, the ca-certificates package is missing. Will add it in the next minor version. 
For your reference, internal issue ID CSI-163 was assigned for this.

**Comment by derselbst** [comment]
While it's true that `ca-certificates` isn't installed, it doesn't solve the problem unfortunately. I've tested it by overriding the command of the wekafs container of the stateful set to
```yaml
      - name: wekafs
        args:
        - -c
        - |
          set -e
          apk update  &&  apk --no-cache add  ca-certificates
          exec /wekafsplugin --drivername=$(CSI_DRIVER_NAME) --v=5 --endpoint=$(CSI_ENDPOINT) --nodeid=$(KUBE_NODE_NAME) --dynamic-path=$(CSI_DYNAMIC_PATH) --csimode=$(X_CSI_MODE) --newvolumeprefix=csivol- --newsnapshotprefix=csisnp- --seedsnapshotprefix=csisnp-seed- --allowautofscreation --allowautofsexpansion --enablemetrics --metricsport=9090 --mutuallyexclusivemountoptions=readcache,writecache,coherent,forcedirect --grpcrequesttimeoutseconds=30 --concurrency.createVolume=5 --concurrency.deleteVolume=1 --concurrency.expandVolume=5 --concurrency.createSnapshot=5 --concurrency.deleteSnapshot=5
        command:
        - /bin/sh
```
`ca-certificates` package is installed, I see that the `/etc/ssl/certs/ca-certificates.crt` file is getting modified but the error persists.

I barely know about Go but could it be that the `tls.Config` is missing the `RootCAs` parameter?

https://github.com/weka/csi-wekafs/blob/1ffb3d094c925a62aac40281de4cdddbf7108a8c/pkg/wekafs/apiclient/apiclient.go#L66
