### ISSUE TITLE
Service Parameters

### ISSUE THREAD

**Issue by Alja9** [weka/csi-wekafs#417]
Hi.

I'm curious why there are some port metrics features but no services that expose those ports :
```
metrics:
  # -- Enable Prometheus Metrics
  enabled: true
  # -- Metrics port for Controller Server
  controllerPort: 9090
  # -- Provisioner metrics port
  provisionerPort: 9091
  # -- Resizer metrics port
  resizerPort: 9092
  # -- Snapshotter metrics port
  snapshotterPort: 9093
  # -- Metrics port for Node Serer
  nodePort: 9094
  # -- Attacher metrics port
  attacherPort: 9095
```
https://github.com/weka/csi-wekafs/blob/7acb515f553b6647bf9d212ea71984fa09f27552/charts/csi-wekafsplugin/values.yaml#L113C1-L127

I don't see any services in `values.yaml` file and in the chart templates, is it possible to add template service parameters as follows :
```
service:
    type: ClusterIP
    ports: []
    nodePorts: ""
    clusterIP: ""
    externalTrafficPolicy: Cluster
    labels: {}
    annotations: {}
    extraPorts: []
```
