### ISSUE TITLE
PV's nodeAffinity should be inherited from storageClass

### ISSUE THREAD

**Issue by derselbst** [weka/csi-wekafs#424]
Hi Sergey,

I'm not sure if that's the right place to address this but I'll try.

We are using a Kubernetes cluster, where only a few worker nodes have access to the Weka storage. For such a use-case, the docs outline at various places (e.g. [here](https://github.com/weka/csi-wekafs/blob/7acb515f553b6647bf9d212ea71984fa09f27552/examples/fsgroup/csi-app-fsgroup.yaml#L12)) that it is common practice to specify an affinity `topology.csi.weka.io/global: "true"` for the pod or deployment. This works well with any deployment manifests, that are under our control.

However, we're also working with Kubeflow. In Kubeflow, most of the options provided by the YAML manifest are abstracted away. I.e. when trying to mount a Weka volume in a Kubeflow pipeline, we have no control over the affinity of the pipeline pod. The pipeline pod will be scheduled to a wrong node and cannot start up.

To circumvent this, one can specify the `nodeAffinity` in the manifest of the PersistentVolume instead. This works well for statically provisioned volumes, causing any pod trying to mount this volume to adhere to the affinity given by the PV.

For dynamically created ones, I was hoping to specify the topology in the storageclass, i.e. something like so:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: weka-dir
provisioner: csi.weka.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
allowedTopologies:
  - matchLabelExpressions:
    - key: topology.csi.weka.io/global
      values:
        - "true"
parameters:
...
```

Unfortunately, the `allowedTopologies` won't get applied to the PV after the PVC is created. That is behavior under control of csi-weka? Can it be fixed so that the PV becomes something like this:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-weka
spec:
  storageClassName: weka-dir
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.csi.weka.io/global
          operator: In
          values:
            - "true"
  csi:
    driver: csi.weka.io
    volumeHandle: ...
```

Edit: Forgot to mention that we did use latest 2.5.1 release

**Comment by sergeyberezansky** [comment]
@derselbst, Hi, how are you?
Thank you for submitting the request.

Actually, this is partially covered in version 2.6.0 that just released.
Instead of taking this from storageClass, the nodeAffinity is added via the topology awareness feature.
Now dynamically created PVs have this part even if not specified in storage-class:

```
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.csi.weka.io/global
          operator: In
          values:
            - "true"
 ```
